application: gonuts-io
version: dev
runtime: go
api_version: go1.1beta

inbound_services:
- warmup

handlers:
- url: /-/public
  static_dir: public

- url: /favicon\.(.*)
  static_files: public/favicon.\1
  upload: public/favicon.(.*)
- url: /apple-touch-icon(.*)\.png
  static_files: public/apple-touch-icon\1.png
  upload: public/apple-touch-icon(.*).png

- url: /robots\.txt
  static_files: public/robots.txt
  upload: public/robots.txt
  mime_type: text/plain

- url: /-/LICENSE
  static_files: LICENSE
  upload: LICENSE
  mime_type: text/plain

- url: /debug/(vars|pprof)
  script: _go_app
  login: admin

- url: /_ah/cron
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
