application: gonuts-io
version: 1
runtime: go
api_version: go1

inbound_services:
- warmup

handlers:
- url: /-/public
  static_dir: public
- url: /favicon\.ico
  static_files: public/favicon.ico
  upload: public/favicon\.ico
- url: /robots\.txt
  static_files: public/robots.txt
  upload: public/robots\.txt
- url: /.*
  script: _go_app
